-- **************************************

-- DATABASE TECHNOLOGY LAB - EXERCISE 01
-- PARANTHAGAN S, ROLL NO: 091, IT - "B"

-- **************************************

-- CREATING MUSICIAN TABLE
CREATE TABLE MUSICIAN (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    BIRTHPLACE VARCHAR(255)
);

-- CREATING ARTIST TABLE
CREATE TABLE ARTIST (
    ARID INT PRIMARY KEY,
    ARNAME VARCHAR(255)
);

-- CREATING STUDIO TABLE
CREATE TABLE STUDIO (
    NAME VARCHAR(255) PRIMARY KEY,
    ADDRESS VARCHAR(255),
    PHONE INT
);

-- CREATING ALBUM TABLE
CREATE TABLE ALBUM (
    AID INT PRIMARY KEY,
    NAME VARCHAR(255),
    YEAROFRELEASE INT,
    NOOFTRACKS INT,
    STUDIOOFRECORDING VARCHAR(255),
    GENRE VARCHAR(255),
    MUSICIANID INT,
    FOREIGN KEY (MUSICIANID) REFERENCES MUSICIAN(ID)
);

-- CREATING SONG TABLE
CREATE TABLE SONG (
    TRACKNUMBER INT PRIMARY KEY,
    AID INT,
    NAME VARCHAR(255),
    LENGTH INT,
    GENRE VARCHAR(255)
);

-- CREATING SUNGBY TABLE
CREATE TABLE SUNGBY (
    AID INT,
    TRACKNUMBER INT,
    ARID INT,
    RECORDINGDATE VARCHAR(255)
);

-- Add UNIQUE constraint to artist name
ALTER TABLE ARTIST
ADD CONSTRAINT UNIQUE_ARTIST_NAME UNIQUE (ARNAME);

-- Add UNIQUE constraint to studio phone
ALTER TABLE STUDIO
ADD CONSTRAINT UNIQUE_STUDIO_PHONE UNIQUE (PHONE);

-- Add genre constraint to the ALBUM table
ALTER TABLE ALBUM
ADD CONSTRAINT CHECK_ALBUM_GENRE CHECK (GENRE IN ('CAR', 'DIV', 'MOV', 'POP'));

-- Add constraint to ensure the year of release is not earlier than 1945
ALTER TABLE ALBUM
ADD CONSTRAINT CHECK_ALBUM_YEAR CHECK (YEAROFRELEASE >= 1945);

-- Add genre constraint to the SONG table
ALTER TABLE SONG
ADD CONSTRAINT CHECK_SONG_GENRE CHECK (GENRE IN ('PHI', 'REL', 'LOV', 'DEV', 'PAT', 'NAT'));

-- Add constraint to ensure the length of each song is greater than 7 for PAT songs
ALTER TABLE SONG
ADD CONSTRAINT CHECK_SONG_LENGTH CHECK (GENRE != 'PAT' OR LENGTH > 7);

-- Create foreign key constraints with ON DELETE CASCADE
ALTER TABLE SONG
ADD CONSTRAINT FK_SONG_ALBUM
FOREIGN KEY (AID)
REFERENCES ALBUM(AID)
ON DELETE CASCADE;


